# Player animation data. Editable in Animation mode; Save to Code rewrites this file.
# Schema, validation and help live in g_animation_authoring.py.

PLAYER_WEAPON_BEZIER_DEFAULTS = {'control_1_radial_fraction': 0.99,
 'control_1_perpendicular': 1.5,
 'control_2_radial_fraction': 0.99,
 'control_2_perpendicular': 1.0}

PLAYER_CUTOUT_RIG_DEFAULTS = {'enabled': True,
 'footfall_phase_degrees': 0.0,
 'movement_blend_response': 14.0,
 'profile_blend_response': 10.0,
 'canvas_size': 32.0,
 'hip': {'x': 16.0, 'y': 22.0},
 'near_hip': {'x': 16.0, 'y': 22.0},
 'far_hip': {'x': 16.0, 'y': 22.0},
 'knee': {'x': 16.0, 'y': 26.0},
 'neck': {'x': 16.0, 'y': 10.0},
 'far_leg_tint': [190, 190, 205, 255],
 'far_arm_tint': [190, 190, 205, 255]}

PLAYER_CUTOUT_GAIT_PROFILES = {'walk': [{'near_upper_leg_degrees': 24.0,
           'near_knee_bend_degrees': 0.0,
           'far_upper_leg_degrees': -24.0,
           'far_knee_bend_degrees': -10.0,
           'near_upper_arm_degrees': -15.0,
           'near_elbow_bend_degrees': 18.0,
           'far_upper_arm_degrees': 1.0,
           'far_elbow_bend_degrees': -20.0,
           'body_y_pixels': 0.0,
           'torso_degrees': 0.5},
          {'near_upper_leg_degrees': 0.0,
           'near_knee_bend_degrees': 22.0,
           'far_upper_leg_degrees': -8.0,
           'far_knee_bend_degrees': 30.0,
           'near_upper_arm_degrees': -4.0,
           'near_elbow_bend_degrees': 24.0,
           'far_upper_arm_degrees': -5.0,
           'far_elbow_bend_degrees': 32.0,
           'body_y_pixels': -0.75,
           'torso_degrees': -1.0},
          {'near_upper_leg_degrees': -24.0,
           'near_knee_bend_degrees': -6.0,
           'far_upper_leg_degrees': 20.0,
           'far_knee_bend_degrees': 4.0,
           'near_upper_arm_degrees': 40.0,
           'near_elbow_bend_degrees': 28.0,
           'far_upper_arm_degrees': -18.0,
           'far_elbow_bend_degrees': 20.0,
           'body_y_pixels': 0.0,
           'torso_degrees': 0.5},
          {'near_upper_leg_degrees': 0.0,
           'near_knee_bend_degrees': -10.0,
           'far_upper_leg_degrees': 7.0,
           'far_knee_bend_degrees': 24.0,
           'near_upper_arm_degrees': 4.0,
           'near_elbow_bend_degrees': 28.0,
           'far_upper_arm_degrees': -6.0,
           'far_elbow_bend_degrees': 28.0,
           'body_y_pixels': -0.75,
           'torso_degrees': 1.5}],
 'run': [{'near_upper_leg_degrees': 65.0,
          'near_knee_bend_degrees': 60.0,
          'far_upper_leg_degrees': -56.0,
          'far_knee_bend_degrees': 24.0,
          'near_upper_arm_degrees': -38.0,
          'near_elbow_bend_degrees': 90.0,
          'far_upper_arm_degrees': 42.0,
          'far_elbow_bend_degrees': 0.0,
          'body_y_pixels': 0.0,
          'torso_degrees': 10.0},
         {'near_upper_leg_degrees': -4.0,
          'near_knee_bend_degrees': 58.0,
          'far_upper_leg_degrees': 12.0,
          'far_knee_bend_degrees': 52.0,
          'near_upper_arm_degrees': -16.0,
          'near_elbow_bend_degrees': 60.0,
          'far_upper_arm_degrees': 24.0,
          'far_elbow_bend_degrees': 48.0,
          'body_y_pixels': -1.75,
          'torso_degrees': 10.5},
         {'near_upper_leg_degrees': -52.0,
          'near_knee_bend_degrees': 18.0,
          'far_upper_leg_degrees': 52.0,
          'far_knee_bend_degrees': 70.0,
          'near_upper_arm_degrees': 60.0,
          'near_elbow_bend_degrees': 10.0,
          'far_upper_arm_degrees': -30.0,
          'far_elbow_bend_degrees': 72.0,
          'body_y_pixels': 0.0,
          'torso_degrees': 10.0},
         {'near_upper_leg_degrees': 6.0,
          'near_knee_bend_degrees': 64.0,
          'far_upper_leg_degrees': -10.0,
          'far_knee_bend_degrees': 54.0,
          'near_upper_arm_degrees': 8.0,
          'near_elbow_bend_degrees': 64.0,
          'far_upper_arm_degrees': -14.0,
          'far_elbow_bend_degrees': 56.0,
          'body_y_pixels': -1.75,
          'torso_degrees': 10.0}]}

PLAYER_CUTOUT_TEXTURES = {'head': 'player_cutout_head_right',
 'torso': 'player_cutout_torso_right',
 'upper_leg': 'player_cutout_upper_leg_right',
 'lower_leg': 'player_cutout_lower_leg_right',
 'upper_arm': 'player_cutout_upper_arm_right',
 'lower_arm': 'player_cutout_lower_arm_right',
 'gun': 'player_cutout_gun_right'}

PLAYER_CUTOUT_DIRECTION_TEXTURES = {'right': {'head': 'player_cutout_head_right',
           'torso': 'player_cutout_torso_right',
           'upper_leg': 'player_cutout_upper_leg_right',
           'lower_leg': 'player_cutout_lower_leg_right',
           'upper_arm': 'player_cutout_upper_arm_right',
           'lower_arm': 'player_cutout_lower_arm_right',
           'gun': 'player_cutout_gun_right'},
 'left': {'head': 'player_cutout_head_right',
          'torso': 'player_cutout_torso_right',
          'upper_leg': 'player_cutout_upper_leg_right',
          'lower_leg': 'player_cutout_lower_leg_right',
          'upper_arm': 'player_cutout_upper_arm_right',
          'lower_arm': 'player_cutout_lower_arm_right',
          'gun': 'player_cutout_gun_right'},
 'up': {'head': 'player_cutout_head_up',
        'torso': 'player_cutout_torso_up',
        'upper_leg': 'player_cutout_upper_leg_up',
        'lower_leg': 'player_cutout_lower_leg_up',
        'upper_arm': 'player_cutout_upper_arm_up',
        'lower_arm': 'player_cutout_lower_arm_up',
        'gun': 'player_cutout_gun_right'},
 'down': {'head': 'player_cutout_head_down',
          'torso': 'player_cutout_torso_down',
          'upper_leg': 'player_cutout_upper_leg_down',
          'lower_leg': 'player_cutout_lower_leg_down',
          'upper_arm': 'player_cutout_upper_arm_down',
          'lower_arm': 'player_cutout_lower_arm_down',
          'gun': 'player_cutout_gun_right'}}

PLAYER_CUTOUT_ARM_DEFAULTS = {'bind_pose': {'shoulder': {'x': 15.5, 'y': 11.0},
               'elbow': {'x': 15.5, 'y': 14.0},
               'hand': {'x': 15.5, 'y': 17.5}},
 'shoulder': {'x': 15.5, 'y': 12.0},
 'far_shoulder': {'x': 14.5, 'y': 11.0},
 'aim_reach': 6.5,
 'gun_grip': {'x': 0.0, 'y': 2.0},
 'gun_source_size': 4.0,
 'gun_muzzle': {'x': 4.0, 'y': 0.5},
 'gun_barrel_direction': {'x': 1.0, 'y': 0.0},
 'gun_grip_perpendicular_offset': 1.0,
 'ik_bend_side': 1.0,
 'far_arm_aim_motion_scale': 0.25}

PLAYER_FLASHLIGHT_POSE_DEFAULTS = {'texture': 'player_cutout_flashlight_right',
 'grip': {'x': 0.0, 'y': 1.0},
 'source_width': 5.0,
 'placeholder_size': {'x': 5.0, 'y': 2.0},
 'placeholder_color': [205, 210, 196, 255],
 'aim_reach': 6.0,
 'grip_perpendicular_offset': -0.75,
 'tip_distance': 5.0}

PLAYER_FRONT_CUTOUT_RIG_DEFAULTS = {'body_hip': {'x': 16.0, 'y': 20.0},
 'neck': {'x': 16.0, 'y': 10.0},
 'leg_bind_pose': {'hip': {'x': 17.5, 'y': 20.0},
                   'knee': {'x': 17.5, 'y': 25.0},
                   'foot': {'x': 17.5, 'y': 31.0}},
 'near_hip': {'x': 17.5, 'y': 20.0},
 'far_hip': {'x': 16.5, 'y': 20.0},
 'down_locomotion_uses_up_leg_art': True,
 'locomotion_leg_art_blend_threshold': 0.02,
 'leg_lateral_scale': 1.0,
 'leg_lift_scale': 1.0,
 'arm_angle_scale': 0.42,
 'elbow_angle_scale': 0.34,
 'torso_angle_scale': 0.12}

PLAYER_FRONT_CUTOUT_LEG_PROFILES = {'up': {'walk': [{'near_knee_x_pixels': 0.35,
                  'near_knee_y_pixels': 0.0,
                  'near_foot_x_pixels': 0.0,
                  'near_foot_y_pixels': 0.0,
                  'far_knee_x_pixels': 0,
                  'far_knee_y_pixels': -0.5,
                  'far_foot_x_pixels': 0.0,
                  'far_foot_y_pixels': -2.0,
                  'body_y_pixels': 0.0,
                  'torso_degrees': 0.5},
                 {'near_knee_x_pixels': -0.1,
                  'near_knee_y_pixels': -0.8,
                  'near_foot_x_pixels': 0.25,
                  'near_foot_y_pixels': -1.6,
                  'far_knee_x_pixels': 0.2,
                  'far_knee_y_pixels': -0.2,
                  'far_foot_x_pixels': 0.4,
                  'far_foot_y_pixels': -0.4,
                  'body_y_pixels': -0.6,
                  'torso_degrees': -0.5},
                 {'near_knee_x_pixels': -0.15,
                  'near_knee_y_pixels': -0.5,
                  'near_foot_x_pixels': -0.0,
                  'near_foot_y_pixels': -2.0,
                  'far_knee_x_pixels': 0.35,
                  'far_knee_y_pixels': 0.0,
                  'far_foot_x_pixels': 0.0,
                  'far_foot_y_pixels': 0.0,
                  'body_y_pixels': 0.0,
                  'torso_degrees': 0.5},
                 {'near_knee_x_pixels': 0.2,
                  'near_knee_y_pixels': -0.2,
                  'near_foot_x_pixels': 0.4,
                  'near_foot_y_pixels': -0.4,
                  'far_knee_x_pixels': -0.1,
                  'far_knee_y_pixels': -0.8,
                  'far_foot_x_pixels': 0.25,
                  'far_foot_y_pixels': -1.6,
                  'body_y_pixels': -0.6,
                  'torso_degrees': 0.5}],
        'run': [{'near_knee_x_pixels': 0.45,
                 'near_knee_y_pixels': 0.0,
                 'near_foot_x_pixels': -1.8,
                 'near_foot_y_pixels': 0.0,
                 'far_knee_x_pixels': -0.2,
                 'far_knee_y_pixels': -1.4,
                 'far_foot_x_pixels': -0.35,
                 'far_foot_y_pixels': -3.6,
                 'body_y_pixels': 0.0,
                 'torso_degrees': 1.0},
                {'near_knee_x_pixels': -0.1,
                 'near_knee_y_pixels': -1.0,
                 'near_foot_x_pixels': -0.2,
                 'near_foot_y_pixels': -2.8,
                 'far_knee_x_pixels': 0.1,
                 'far_knee_y_pixels': -0.8,
                 'far_foot_x_pixels': 0.2,
                 'far_foot_y_pixels': -2.2,
                 'body_y_pixels': -1.5,
                 'torso_degrees': 1.5},
                {'near_knee_x_pixels': -0.2,
                 'near_knee_y_pixels': -1.4,
                 'near_foot_x_pixels': -0.35,
                 'near_foot_y_pixels': -3.6,
                 'far_knee_x_pixels': 0.45,
                 'far_knee_y_pixels': 0.0,
                 'far_foot_x_pixels': -1.8,
                 'far_foot_y_pixels': 0.0,
                 'body_y_pixels': 0.0,
                 'torso_degrees': 1.0},
                {'near_knee_x_pixels': 0.1,
                 'near_knee_y_pixels': -0.8,
                 'near_foot_x_pixels': 0.2,
                 'near_foot_y_pixels': -2.2,
                 'far_knee_x_pixels': -0.1,
                 'far_knee_y_pixels': -1.0,
                 'far_foot_x_pixels': -0.2,
                 'far_foot_y_pixels': -2.8,
                 'body_y_pixels': -1.5,
                 'torso_degrees': 1.5}]},
 'down': {'walk': [{'near_knee_x_pixels': 0.35,
                    'near_knee_y_pixels': 0.0,
                    'near_foot_x_pixels': 0.0,
                    'near_foot_y_pixels': 0.0,
                    'far_knee_x_pixels': -0.15,
                    'far_knee_y_pixels': -0.5,
                    'far_foot_x_pixels': -1.25,
                    'far_foot_y_pixels': -2.0,
                    'body_y_pixels': 0.0,
                    'torso_degrees': 0.5},
                   {'near_knee_x_pixels': -0.1,
                    'near_knee_y_pixels': -0.8,
                    'near_foot_x_pixels': -0.25,
                    'near_foot_y_pixels': -1.6,
                    'far_knee_x_pixels': 0.2,
                    'far_knee_y_pixels': -0.2,
                    'far_foot_x_pixels': 0.4,
                    'far_foot_y_pixels': -0.4,
                    'body_y_pixels': -0.6,
                    'torso_degrees': -0.5},
                   {'near_knee_x_pixels': -0.15,
                    'near_knee_y_pixels': -0.5,
                    'near_foot_x_pixels': -1.25,
                    'near_foot_y_pixels': -2.0,
                    'far_knee_x_pixels': 0.35,
                    'far_knee_y_pixels': 0.0,
                    'far_foot_x_pixels': 0.0,
                    'far_foot_y_pixels': 0.0,
                    'body_y_pixels': 0.0,
                    'torso_degrees': 0.5},
                   {'near_knee_x_pixels': 0.2,
                    'near_knee_y_pixels': -0.2,
                    'near_foot_x_pixels': 0.4,
                    'near_foot_y_pixels': -0.4,
                    'far_knee_x_pixels': -0.1,
                    'far_knee_y_pixels': -0.8,
                    'far_foot_x_pixels': -0.25,
                    'far_foot_y_pixels': -1.6,
                    'body_y_pixels': -0.6,
                    'torso_degrees': 0.5}],
          'run': [{'near_knee_x_pixels': 0.45,
                   'near_knee_y_pixels': 0.0,
                   'near_foot_x_pixels': -1.5,
                   'near_foot_y_pixels': 0.0,
                   'far_knee_x_pixels': -0.2,
                   'far_knee_y_pixels': -1.4,
                   'far_foot_x_pixels': -1.35,
                   'far_foot_y_pixels': -3.6,
                   'body_y_pixels': 0.0,
                   'torso_degrees': 1.0},
                  {'near_knee_x_pixels': -0.1,
                   'near_knee_y_pixels': -1.0,
                   'near_foot_x_pixels': -0.2,
                   'near_foot_y_pixels': -2.8,
                   'far_knee_x_pixels': 0.1,
                   'far_knee_y_pixels': -0.8,
                   'far_foot_x_pixels': 0.2,
                   'far_foot_y_pixels': -2.2,
                   'body_y_pixels': -1.5,
                   'torso_degrees': 1.5},
                  {'near_knee_x_pixels': -0.2,
                   'near_knee_y_pixels': -1.4,
                   'near_foot_x_pixels': -1.35,
                   'near_foot_y_pixels': -3.6,
                   'far_knee_x_pixels': 0.45,
                   'far_knee_y_pixels': 0.0,
                   'far_foot_x_pixels': -1.5,
                   'far_foot_y_pixels': 0.0,
                   'body_y_pixels': 0.0,
                   'torso_degrees': 1.0},
                  {'near_knee_x_pixels': 0.1,
                   'near_knee_y_pixels': -0.8,
                   'near_foot_x_pixels': 0.2,
                   'near_foot_y_pixels': -2.2,
                   'far_knee_x_pixels': -0.1,
                   'far_knee_y_pixels': -1.0,
                   'far_foot_x_pixels': -0.2,
                   'far_foot_y_pixels': -2.8,
                   'body_y_pixels': -1.5,
                   'torso_degrees': 1.5}]}}

PLAYER_FRONT_CUTOUT_ARM_DEFAULTS = {'bind_pose': {'shoulder': {'x': 19.5, 'y': 11.0},
               'elbow': {'x': 20.0, 'y': 15.0},
               'hand': {'x': 20.0, 'y': 19.0}},
 'shoulder': {'x': 19.5, 'y': 11.0},
 'far_shoulder': {'x': 18.5, 'y': 11.0},
 'aim_reach': 6.5,
 'straight_aim_reach_scale': 1.0,
 'down_cross_body_aim_reach': 6.5,
 'down_cross_body_reach_exponent': 1.0,
 'down_cross_body_ik_bend_side': -1.0,
 'gun_grip': {'x': 0.0, 'y': 2.0},
 'gun_source_size': 4.0,
 'gun_grip_perpendicular_offset': 1.0,
 'ik_bend_side': 1.0,
 'far_arm_aim_motion_scale': 0.25}

PLAYER_RELOAD_POSE_DEFAULTS = {'enter_fraction': 0.16,
 'exit_fraction': 0.14,
 'side': {'aim_direction': {'x': 0.42, 'y': 0.91},
          'support_hand_from_gun': {'x': 0.0, 'y': 0.0},
          'support_bend_side': 1.0},
 'down': {'near_hand_from_body_hip': {'x': 1.0, 'y': -3.5},
          'far_hand_from_body_hip': {'x': 1.0, 'y': -3.5},
          'gun_from_body_hip': {'x': 0.0, 'y': -3.5},
          'gun_degrees': 90.0,
          'near_bend_side': 1.0,
          'far_bend_side': 1.0},
 'up': {'near_hand_from_body_hip': {'x': 0.8, 'y': -2.5},
        'far_hand_from_body_hip': {'x': 0.8, 'y': -2.5},
        'gun_from_body_hip': {'x': 0.0, 'y': -1.8},
        'gun_degrees': 90.0,
        'near_bend_side': 1.0,
        'far_bend_side': 1.0}}

PLAYER_FRONT_CUTOUT_ARM_PROFILES = {'up': {'walk': [{'near_upper_arm_degrees': -15.0,
                  'near_elbow_bend_degrees': 18.0,
                  'far_upper_arm_degrees': 15.0,
                  'far_elbow_bend_degrees': -45.0},
                 {'near_upper_arm_degrees': -4.0,
                  'near_elbow_bend_degrees': 12.0,
                  'far_upper_arm_degrees': -5.0,
                  'far_elbow_bend_degrees': 12.0},
                 {'near_upper_arm_degrees': 40.0,
                  'near_elbow_bend_degrees': 28.0,
                  'far_upper_arm_degrees': -18.0,
                  'far_elbow_bend_degrees': 20.0},
                 {'near_upper_arm_degrees': 4.0,
                  'near_elbow_bend_degrees': 12.0,
                  'far_upper_arm_degrees': -1.0,
                  'far_elbow_bend_degrees': 12.0}],
        'run': [{'near_elbow_x_pixels': 0.0,
                 'near_elbow_y_pixels': -0.8,
                 'near_hand_x_pixels': -2.0,
                 'near_hand_y_pixels': -4.4,
                 'far_elbow_x_pixels': 0.0,
                 'far_elbow_y_pixels': 0.15,
                 'far_hand_x_pixels': 0.0,
                 'far_hand_y_pixels': 0.4},
                {'near_elbow_x_pixels': 0.0,
                 'near_elbow_y_pixels': -0.45,
                 'near_hand_x_pixels': 0.0,
                 'near_hand_y_pixels': -1.2,
                 'far_elbow_x_pixels': 0.0,
                 'far_elbow_y_pixels': -0.2,
                 'far_hand_x_pixels': 0.0,
                 'far_hand_y_pixels': -0.6},
                {'near_elbow_x_pixels': 0.0,
                 'near_elbow_y_pixels': 0.15,
                 'near_hand_x_pixels': 0.0,
                 'near_hand_y_pixels': 0.4,
                 'far_elbow_x_pixels': 0.0,
                 'far_elbow_y_pixels': -0.8,
                 'far_hand_x_pixels': -2.0,
                 'far_hand_y_pixels': -4.5},
                {'near_elbow_x_pixels': 0.0,
                 'near_elbow_y_pixels': -0.2,
                 'near_hand_x_pixels': 0.0,
                 'near_hand_y_pixels': -0.6,
                 'far_elbow_x_pixels': 0.0,
                 'far_elbow_y_pixels': -0.45,
                 'far_hand_x_pixels': 0.0,
                 'far_hand_y_pixels': -1.2}]},
 'down': {'walk': [{'near_upper_arm_degrees': -15.0,
                    'near_elbow_bend_degrees': 18.0,
                    'far_upper_arm_degrees': 10.0,
                    'far_elbow_bend_degrees': -50.0},
                   {'near_upper_arm_degrees': -4.0,
                    'near_elbow_bend_degrees': 14.0,
                    'far_upper_arm_degrees': -1.0,
                    'far_elbow_bend_degrees': 12.0},
                   {'near_upper_arm_degrees': 40.0,
                    'near_elbow_bend_degrees': 28.0,
                    'far_upper_arm_degrees': -18.0,
                    'far_elbow_bend_degrees': 20.0},
                   {'near_upper_arm_degrees': 4.0,
                    'near_elbow_bend_degrees': 28.0,
                    'far_upper_arm_degrees': -1.0,
                    'far_elbow_bend_degrees': 12.0}],
          'run': [{'near_elbow_x_pixels': 0.0,
                   'near_elbow_y_pixels': -2.8,
                   'near_hand_x_pixels': 1.0,
                   'near_hand_y_pixels': -1.0,
                   'far_elbow_x_pixels': 0.0,
                   'far_elbow_y_pixels': 0.15,
                   'far_hand_x_pixels': -1.4,
                   'far_hand_y_pixels': -2.4},
                  {'near_elbow_x_pixels': 0.0,
                   'near_elbow_y_pixels': -0.45,
                   'near_hand_x_pixels': 0.0,
                   'near_hand_y_pixels': -1.2,
                   'far_elbow_x_pixels': 0.0,
                   'far_elbow_y_pixels': -0.2,
                   'far_hand_x_pixels': 0.0,
                   'far_hand_y_pixels': -0.6},
                  {'near_elbow_x_pixels': 0.0,
                   'near_elbow_y_pixels': 0.15,
                   'near_hand_x_pixels': -1.0,
                   'near_hand_y_pixels': -1.0,
                   'far_elbow_x_pixels': 0.0,
                   'far_elbow_y_pixels': -0.8,
                   'far_hand_x_pixels': 0.0,
                   'far_hand_y_pixels': -2.0},
                  {'near_elbow_x_pixels': 0.0,
                   'near_elbow_y_pixels': -0.2,
                   'near_hand_x_pixels': 0.0,
                   'near_hand_y_pixels': -0.6,
                   'far_elbow_x_pixels': 0.0,
                   'far_elbow_y_pixels': -0.45,
                   'far_hand_x_pixels': 0.0,
                   'far_hand_y_pixels': -1.2}]}}
