# Redhead animation data. Editable in Animation mode; Save to Code rewrites this file.
# Schema, validation and help live in g_animation_authoring.py.

REDHEAD_CUTOUT_TEXTURES = {'right': {'head': 'redhead_cutout_head_right',
           'torso': 'redhead_cutout_torso_right',
           'upper_leg': 'redhead_cutout_upper_leg_right',
           'lower_leg': 'redhead_cutout_lower_leg_right',
           'upper_arm': 'redhead_cutout_upper_arm_right',
           'lower_arm': 'redhead_cutout_lower_arm_right'},
 'up': {'head': 'redhead_cutout_head_up',
        'torso': 'redhead_cutout_torso_up',
        'upper_leg': 'redhead_cutout_upper_leg_up',
        'lower_leg': 'redhead_cutout_lower_leg_up',
        'upper_arm': 'redhead_cutout_upper_arm_up',
        'lower_arm': 'redhead_cutout_lower_arm_up'},
 'down': {'head': 'redhead_cutout_head_down',
          'torso': 'redhead_cutout_torso_down',
          'upper_leg': 'redhead_cutout_upper_leg_down',
          'lower_leg': 'redhead_cutout_lower_leg_down',
          'upper_arm': 'redhead_cutout_upper_arm_down',
          'lower_arm': 'redhead_cutout_lower_arm_down'}}

REDHEAD_CUTOUT_RIG_DEFAULTS = {'enabled': True,
 'canvas_size': 24.0,
 'footfall_phase_degrees': 0.0,
 'movement_blend_response': 16.0,
 'profile_blend_response': 8.0,
 'run_blend_start_speed_fraction': 0.52,
 'run_blend_full_speed_fraction': 0.9,
 'far_limb_tint': [182, 188, 184, 255],
 'side': {'hip': {'x': 11.5, 'y': 16.5},
          'near_hip': {'x': 11.5, 'y': 16.5},
          'far_hip': {'x': 12.25, 'y': 16.5},
          'knee': {'x': 11.5, 'y': 18.5},
          'foot': {'x': 11.5, 'y': 21.0},
          'neck': {'x': 11.5, 'y': 13.0},
          'shoulder': {'x': 12.5, 'y': 13.5},
          'near_shoulder': {'x': 12.5, 'y': 13.5},
          'far_shoulder': {'x': 11.75, 'y': 13.5},
          'elbow': {'x': 12.5, 'y': 15.5},
          'hand': {'x': 12.5, 'y': 17.5}},
 'front': {'hip': {'x': 12.0, 'y': 16.5},
           'limb_hip': {'x': 13.5, 'y': 16.5},
           'knee': {'x': 13.5, 'y': 18.5},
           'foot': {'x': 13.5, 'y': 21.0},
           'neck': {'x': 11.5, 'y': 13.0},
           'shoulder': {'x': 13.5, 'y': 13.5},
           'elbow': {'x': 15.5, 'y': 14.5},
           'hand': {'x': 17.5, 'y': 16.5}}}

REDHEAD_CUTOUT_GAIT_PROFILES = {'walk': [{'near_upper_leg_degrees': -26.0,
           'near_knee_bend_degrees': 5.0,
           'far_upper_leg_degrees': 26.0,
           'far_knee_bend_degrees': 10.0,
           'near_upper_arm_degrees': 18.0,
           'near_elbow_bend_degrees': -12.0,
           'far_upper_arm_degrees': -20.0,
           'far_elbow_bend_degrees': -18.0,
           'body_x_pixels': 0.1875,
           'body_y_pixels': 0.0,
           'side_torso_degrees': 4.0,
           'front_torso_degrees': 1.5,
           'near_front_leg_y_pixels': 0.0,
           'far_front_leg_y_pixels': 0.0,
           'front_arm_angle_scale': 0.65,
           'front_elbow_angle_scale': 0.5},
          {'near_upper_leg_degrees': 12.0,
           'near_knee_bend_degrees': 55.0,
           'far_upper_leg_degrees': 0.0,
           'far_knee_bend_degrees': 0.0,
           'near_upper_arm_degrees': 0.0,
           'near_elbow_bend_degrees': -15.0,
           'far_upper_arm_degrees': 0.0,
           'far_elbow_bend_degrees': -15.0,
           'body_x_pixels': 0.025,
           'body_y_pixels': -0.4,
           'side_torso_degrees': -1.0,
           'front_torso_degrees': 0.15,
           'near_front_leg_y_pixels': -1.4,
           'far_front_leg_y_pixels': 0.0,
           'front_arm_angle_scale': 0.65,
           'front_elbow_angle_scale': 0.5},
          {'near_upper_leg_degrees': 26.0,
           'near_knee_bend_degrees': 10.0,
           'far_upper_leg_degrees': -26.0,
           'far_knee_bend_degrees': 5.0,
           'near_upper_arm_degrees': -20.0,
           'near_elbow_bend_degrees': -18.0,
           'far_upper_arm_degrees': 18.0,
           'far_elbow_bend_degrees': -12.0,
           'body_x_pixels': -0.1875,
           'body_y_pixels': 0.0,
           'side_torso_degrees': -4.0,
           'front_torso_degrees': -1.5,
           'near_front_leg_y_pixels': 0.0,
           'far_front_leg_y_pixels': 0.0,
           'front_arm_angle_scale': 0.65,
           'front_elbow_angle_scale': 0.5},
          {'near_upper_leg_degrees': 0.0,
           'near_knee_bend_degrees': 0.0,
           'far_upper_leg_degrees': 12.0,
           'far_knee_bend_degrees': 55.0,
           'near_upper_arm_degrees': 0.0,
           'near_elbow_bend_degrees': -15.0,
           'far_upper_arm_degrees': 0.0,
           'far_elbow_bend_degrees': -15.0,
           'body_x_pixels': -0.025,
           'body_y_pixels': -0.4,
           'side_torso_degrees': 1.0,
           'front_torso_degrees': -0.15,
           'near_front_leg_y_pixels': 0.0,
           'far_front_leg_y_pixels': -1.4,
           'front_arm_angle_scale': 0.65,
           'front_elbow_angle_scale': 0.5}],
 'run': [{'near_upper_leg_degrees': -55.0,
          'near_knee_bend_degrees': 20.0,
          'far_upper_leg_degrees': 42.0,
          'far_knee_bend_degrees': 45.0,
          'near_upper_arm_degrees': 32.0,
          'near_elbow_bend_degrees': -85.0,
          'far_upper_arm_degrees': -65.0,
          'far_elbow_bend_degrees': -65.0,
          'body_x_pixels': 0.1125,
          'body_y_pixels': 0.0,
          'side_torso_degrees': 14.0,
          'front_torso_degrees': 1.2,
          'near_front_leg_y_pixels': 0.0,
          'far_front_leg_y_pixels': 0.0,
          'front_arm_angle_scale': 0.3,
          'front_elbow_angle_scale': 0.18},
         {'near_upper_leg_degrees': 10.0,
          'near_knee_bend_degrees': 105.0,
          'far_upper_leg_degrees': -18.0,
          'far_knee_bend_degrees': 20.0,
          'near_upper_arm_degrees': -15.0,
          'near_elbow_bend_degrees': -80.0,
          'far_upper_arm_degrees': -10.0,
          'far_elbow_bend_degrees': -85.0,
          'body_x_pixels': -0.05,
          'body_y_pixels': -1.8,
          'side_torso_degrees': 20.0,
          'front_torso_degrees': -0.8999999999999999,
          'near_front_leg_y_pixels': -2.6,
          'far_front_leg_y_pixels': 0.0,
          'front_arm_angle_scale': 0.3,
          'front_elbow_angle_scale': 0.18},
         {'near_upper_leg_degrees': 42.0,
          'near_knee_bend_degrees': 45.0,
          'far_upper_leg_degrees': -55.0,
          'far_knee_bend_degrees': 20.0,
          'near_upper_arm_degrees': -65.0,
          'near_elbow_bend_degrees': -65.0,
          'far_upper_arm_degrees': 32.0,
          'far_elbow_bend_degrees': -85.0,
          'body_x_pixels': -0.1125,
          'body_y_pixels': 0.0,
          'side_torso_degrees': 13.0,
          'front_torso_degrees': -1.2,
          'near_front_leg_y_pixels': 0.0,
          'far_front_leg_y_pixels': 0.0,
          'front_arm_angle_scale': 0.3,
          'front_elbow_angle_scale': 0.18},
         {'near_upper_leg_degrees': -18.0,
          'near_knee_bend_degrees': 20.0,
          'far_upper_leg_degrees': 10.0,
          'far_knee_bend_degrees': 105.0,
          'near_upper_arm_degrees': -10.0,
          'near_elbow_bend_degrees': -85.0,
          'far_upper_arm_degrees': -15.0,
          'far_elbow_bend_degrees': -80.0,
          'body_x_pixels': 0.0625,
          'body_y_pixels': -1.8,
          'side_torso_degrees': 22.0,
          'front_torso_degrees': 0.8999999999999999,
          'near_front_leg_y_pixels': 0.0,
          'far_front_leg_y_pixels': -2.6,
          'front_arm_angle_scale': 0.3,
          'front_elbow_angle_scale': 0.18}]}

REDHEAD_ANIMATION_DEBUG_POSE_NAMES = {'walk': ('right-foot plant', 'lifted recovery', 'left-foot plant', 'opposite recovery'),
 'run': ('right-foot impact', 'flight / recovery', 'left-foot impact', 'opposite flight')}
